spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AtlantaMovie?useSSL=true
    username: root
    password: a3108326251
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    com.lrg: debug
  file:
    name: log/demo-dev.log
